### ISSUE TITLE
Filtering and node selection

### ISSUE THREAD

**Issue by sajithpc** [iVantage/angular-ivh-treeview#140] opened 2016-07-16 12:49 UTC
Below given example provides option to filter the tree via search input box.
http://plnkr.co/edit/wOo98cSXa12rRLZO85lr?p=preview

As per documentation, Keep in mind that selections (i.e. checkboxes) are filter independent. In other words, filtered away nodes will still be affected by parent selection changes.

For example, filtered shows two entries with a parent. When I selected the parent, it selected the two childrens but it internally selected all the childrens under the parent. What expected is it should select only the filtered childrens instead of all childrens present under the parent.

Is there any option available to do this.

**Comment by jtrussell** [comment] 2016-07-18 16:55
There's no option for this out of the box but you can achieve it by dropping in your own checkboxes to update selections as you like.

Duplicate of #96

**Closed by jtrussell** 2016-07-18 16:55 UTC
Labels: question
