### ISSUE TITLE
select all function check only root node

### ISSUE THREAD

**Issue by jbjumbojb** [iVantage/angular-ivh-treeview#120] opened 2016-03-30 07:39 UTC
![image](https://cloud.githubusercontent.com/assets/682524/14135050/33771c76-f685-11e5-81dc-7b9e8e64f3ed.png)

http://jsbin.com/fifoki/2/edit?html,js,output

**Comment by jbjumbojb** [comment] 2016-03-30 08:36
this issue not occur if I'm not change children attribute name

**Comment by jtrussell** [comment] 2016-03-31 00:43
Duplicate of #106.

Options set on the directive are not global in effect. You'll want to either override the global options or provide your custom ones to `ivhTreeviewMgr`, for example:

```
ivhTreeviewMgr.selectAll(myTree, {
  childrenAttribute: 'subCategories'
});
```

**Closed by jtrussell** 2016-03-31 00:43 UTC
