### ISSUE TITLE
Show 'No records found' if no match is found 

### ISSUE THREAD

**Issue by pryashrma** [iVantage/angular-ivh-treeview#202] opened 2017-07-24 05:31 UTC
Hi, I'm trying to print "No records found" when the filtering does not match any records. Currently, the tree simply disappears.  I have used "ivh-treeview-filter" option. 

Please provide some direction.

Thanks

**Comment by jtrussell** [comment] 2017-09-04 21:04
A duplicate of #192 - I don't think we have an (elegant?) solution for this at the moment.

**Closed by jtrussell** 2017-09-04 21:04 UTC
